### ISSUE TITLE
v0.23.0 Restarts a node using a snapshot. The node is stuck out of sync

### ISSUE THREAD

**Issue by blocknodehub** [Kava-Labs/kava#1593]
![截屏2023-05-18 11 36 11](https://github.com/Kava-Labs/kava/assets/100512407/115b830a-e935-4d5d-992a-0f2afbd27d9b)

**Comment by xingdalu** [comment]
I have the same problem.

**Comment by nddeluca** [comment]
Hi @blocknodehub, block 4832500 takes a long time to commit, especially on archive nodes.  We've seen nodes with large state take ~1 hour to commit the block.  This is due to the large amount of key changes during the cosmos v0.45-v0.46 module migrations.

The node will eventually finish the commit and sync more normally for blocks 4832501+

**Comment by pirtleshell** [comment]
closing this for now, please reopen & reply with any problems if there are some @blocknodehub 

thanks for running a node! the upgrade took a really long time, but once its running you should see a notable change in performance and latency of the apis.
