### ISSUE TITLE
CDPs can fall below liquidation ratio indefinitely and be improperly rescued

### ISSUE THREAD

**Issue by denalimarsh** [Kava-Labs/kava#367]
Accumulated fees are only applied to a CDP on deposit, withdraw, draw, or repay. A CDP can accumulate fees and fall below the liquidation ratio indefinitely without being liquidated. In the event of a deposit/repay, the CDPs collateralization ratio is updated before it is liquidated, as seizing/liquidation doesn't occur until the start of the next block. A CDP can, therefore, fall below the liquidation ratio indefinitely and be rescued via deposit at any time.

Changes in asset price do not mitigate this issue, as `LiquidateCdps()` pulls an asset's current price and uses it to gather CDPs below the liquidation ratio, but any accumulated fees are not reflected in these calculations.

**Comment by denalimarsh** [comment]
This is related to https://github.com/Kava-Labs/kava/issues/335, but is not a duplicate.

**Comment by denalimarsh** [comment]
Consequently, any deposit that does not result in the CDP's CR being greater than the LR will liquidate the CDP. From a user's perspective, they've just added collateral only to have it immediately seized before being able to draw any debt on that collateral.

**Comment by karzak** [comment]
To clarify the exact conditions here, a CDP can fall below liquidation threshold due to fees, but in order to remain there without intervention, the price would have to never break against the cdp. Perhaps for very old CDPs the delta between being liquidated by fees and being liquidated by price could be large, but in general, I would expect CDPs in that state to get liquidated by price fluctuations with high probability. 

This issue is still worth mitigating though, and I would be in favor of adding some threshold for fee calculation in the begin blocker, as outlined in https://github.com/Kava-Labs/kava/issues/366#issuecomment-583894839

**Comment by denalimarsh** [comment]
What do you mean by 'the price would have to never break against the cdp'?

**Comment by karzak** [comment]
As an example. Imagine

CDP: 
Collateral Value at time of creation: $100
Debt value: $50
Required collateral ratio: 150%

Imagine at some point after creation, the CDP looks like this, due to changes in the price of the collateral and the accumulation of fees:

CDP: 
Collateral Value: $75.1
Debt value: $50
Fees: $0
ActualFees: $1

Note that Fees is all that's stored on the CDP object, but the actual fees is updated any time the owner/depositor wants to change the state of a CDP. 

By our current liquidation method, this CDP would not be liquidated, because it would have a collateral:debt ratio > 150%. In my suggested mitigation, we would select CDPs with collateral ratio between say, 150% and 157.5%, and call `UpdateFees` on them. If we implemented that, then this cdp would get liquidated, because (collateral + actual fees < 150%). 

However, even with no mitigations, this CDP would still be extremely likely to get liquidated, because the price of the collateral is likely to go below $75 at some point, just due to random fluctuation in the collateral asset's price. That's what I mean by 'the price would have to never break against the CDP'. So, in reality, what we're mitigating against is short windows of time where a CDP 'should' get liquidated, but doesn't.

**Comment by denalimarsh** [comment]
Ah okay, I understand. For a relatively stable asset the longer the CDP is open the higher the likelihood that the actual fees should cause CDP liquidation. In addition to your proposal, we could mitigate this case by also checking CDP creation/most recent interaction block and updating fees on the oldest CDPs.

**Comment by karzak** [comment]
Closed via #449
